#!/bin/sh
# Writes the Homebrew formula for release TAG to stdout, pointing at the
# release's prebuilt binaries and their checksums.
#
#   .github/scripts/homebrew-formula.sh v0.2.0 build/checksums.txt > sonarc.rb
set -eu

tag="$1"
sums="$2"
repo="${GITHUB_REPOSITORY:-sonarc-dev/sonarc}"
base="https://github.com/$repo/releases/download/$tag"

sum() {
	s="$(awk -v n="$1" '$2 == n { print $1 }' "$sums")"
	[ -n "$s" ] || { echo "no checksum for $1 in $sums" >&2; exit 1; }
	echo "$s"
}

cat <<FORMULA
# Generated by the sonarc release workflow; edits here are overwritten.
class Sonarc < Formula
  desc "Modeless terminal editor for navigating huge codebases over ssh"
  homepage "https://sonarc-dev.github.io/sonarc/"
  version "${tag#v}"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/sonarc-darwin-arm64"
      sha256 "$(sum sonarc-darwin-arm64)"
    end
    on_intel do
      url "$base/sonarc-darwin-amd64"
      sha256 "$(sum sonarc-darwin-amd64)"
    end
  end

  on_linux do
    on_arm do
      url "$base/sonarc-linux-arm64"
      sha256 "$(sum sonarc-linux-arm64)"
    end
    on_intel do
      url "$base/sonarc-linux-amd64"
      sha256 "$(sum sonarc-linux-amd64)"
    end
  end

  def install
    bin.install Dir["sonarc-*"].first => "sonarc"
  end

  test do
    assert_match "sonarc v#{version}", shell_output("#{bin}/sonarc -version")
  end
end
FORMULA
